import neostandard, { resolveIgnoresFromGitignore } from 'neostandard'

export default neostandard({
  ts: true,
  ignores: [
    ...resolveIgnoresFromGitignore(),
    'e2e-v5/app/.well-known/',
    'e2e-v4/app/.well-known/',
    // Auto-generated by `next build` — Next owns the formatting.
    'e2e-v5/next-env.d.ts',
    'e2e-v4/next-env.d.ts',
    'packages/world/dist/',
    'packages/workflow/dist/',
    'packages/workflow-fastify/dist/',
    'examples/*/.well-known/',
  ],
})
